### ISSUE TITLE
My suggestions 

### ISSUE THREAD

**Issue by Arakistech** [rishikesh2715/RP2040-Motion-Sense-Board#3]
Great work!

1- Can you check if your design works with PicoQuake firmware? 

https://www.tindie.com/products/plab/picoquake-usb-vibration-sensor/
https://github.com/PLab-SI/PicoQuake

It is also a RP2040 with a ICM-42688 over SPI and USB. 

2- Would it be possible to add an optional microSD card slot?

3- Why don´t you think on using a standard Feather form factor for your board? I would be interested in using it as a shield for Stratus board with nRF9161 https://www.crowdsupply.com/conexio/conexio-stratus-pro if your board would have a Feather form factor and could be enabled/disabled via EN pin, it would be great for low power IoT.

**Comment by rishikesh2715** [comment]
Yeah, I can include a microSD card slot, but I am pretty sure RP2040 only has one SPI channel so I will have to switch the communication protocol for the IMU to I2C. 

And I can design the form factor to be match the Adafruit feather boards.
